### ISSUE TITLE
Samtools dependencies

### ISSUE THREAD

**Issue by PlatonB** [samtools/www.htslib.org#24]
[List of Samtools dependencies](https://samtools.github.io/bcftools/howtos/install.html) for Ubuntu is not up to date.
Current dependencies (Ubuntu 18.04):
```
gcc
make
zlib1g-dev
libbz2-dev
liblzma-dev
libcurl4-openssl-dev
libssl-dev
libncurses5-dev
```

**Comment by jmarshall** [comment]
The page in question actually comes from the **gh-pages** branch of **bcftools**.

However I've transferred this issue here on the basis that it would be good to expand the installation information at <https://www.htslib.org/download/> to contain the list of prerequisites (and some of the other details) that have been added to each project's _INSTALL_ file since the htslib.org web site was started.

**Comment by jkbonfield** [comment]
Personally I think having multiple places to document the same list is likely to cause more stale content, so I don't really see the benefit in replicating bits of the INSTALL documentation into the download page.

I'll fix the bcftools one though as it already exists.
